### PR TITLE
added  Lesson1-Git/newFile.js

### PR DESCRIPTION
**Pull request by kirkSam**
an experiment

### CODE REVIEW

**Comment by kirkSam** [comment]
added newFile.js

**Comment by kirkSam** [comment]
I submitted a pull request because the deadline was reached. Numerous tests did not pass due to the fact that I put them in the wrong place. I have been hustling to correct this but the deadline was reached before I finished.

**Comment by mitchellwright** [comment]
Hi Sam, can you please reach out to me on Slack?

**Comment by kirkSam** [comment]
This pull request is for the Homework from CS 11. The pull request is also generating conflicts that I do not comprehend. I have contacted Git Hub for insight on resolving the conflicts.

**Comment by kirkSam** [comment]
I am in the process of resolving the conflicts listed witht the assistance of GitHub support...

**Comment by kirkSam** [comment]
I have completed the Mini-Bootcamp Lessons 1 - 8 as well as the Feynman Writing Prompts. I am looking forward to feedback and the May 7th start. I am continuing with Lessons 9-12.

**Pull request closed without merging**
